JC=javac
JFLAGS=

%.class: %.java
	$(JC) $(FLAGS) $<

all: Binary.class Foo.class FizzBuzz.class Simple.class Hello.class
	@# Done

clean:
	rm -f Binary.class Foo.class FizzBuzz.class Simple.class Hello.class

