Simple.class: Simple.java
	javac Simple.java

FizzBuzz.class: FizzBuzz.java
	javac FizzBuzz.java

Binary.class: Binary.java
	javac Binary.java

all: Simple.class FizzBuzz.class Binary.class
	echo done

.PHONY: all
